### ISSUE TITLE
Broken in hass 0.96.0

### ISSUE THREAD

**Issue by ways** [mairas/hysen#18]
Hi

Just upgraded to home-assistant 0.96.0 and get this message on config test:

```
Failed config
  General Errors: 
    - Platform not found: climate.hysen

Successful config (partial)
1
```

Config which has worked and not changed for a long time:

```
  - platform: hysen
    scan_interval: 15
    devices:
      kjellerbad:
        name: Kjellerbad
        host: 192.168.1.25
        mac: '34:ea:34:7a:e7:fe'
        target_temp_default: 25
        target_temp_step: 1
        sync_clock_time_per_day: True
        #current_temp_from_sensor_override: 0 # if this is set to 1 always use the internal sensor to report current temp, if 1 always use external sensor to report current temp.
        update_timeout: 5
```

Did a git pull to latest version. No change.
